

<Device>
    FloatLayout:
        id: deviceLayout
        size: root.width,root.height*0.83
        canvas.before:
            Color:
                #rgba: 1, 0.3, 0.2, 1
                rgb: utils.get_color_from_hex('#0080ff')
            Rectangle:
                pos: self.pos
                size: self.size

        Button:
            text: "Device"
            size: 100, 100
            size_hint: None, None # <---
            pos_hint: {"x":0, "y":0.9}
